version: 2

jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker build \
              -f Dockerfile \
              -t ${CIRCLE_PROJECT_REPONAME}:latest \
              -t ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM} .
      - run:
          name: Push Docker image to repository
          command: |
            echo $GCLOUD_SERVICE_KEY_BASE64 | base64 --decode -i > ${HOME}/gcloud-service-auth.json
            # Set GCP credentials and config
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-auth.json
            gcloud auth configure-docker

            # tag docker image and upload
            gke_image=eu.gcr.io/${GCP_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}
            if [[ $CIRCLE_BRANCH = master ]]; then
              docker tag ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM} ${gke_image}:master
            fi
            docker tag ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM} ${gke_image}:${CIRCLE_SHA1}
            docker push $gke_image

workflows:
  version: 2
  pipeline:
    jobs:
      - build